server.port=8085

spring.datasource.url=jdbc:postgresql://localhost:5432/blog-db
spring.datasource.username={seu-usuario-aqui}
spring.datasource.password={sua-senha-aqui}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
jwt.secret=uma-string-bem-grande-e-segura-para-chave-jwt-2026

logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=DEBUG


